[project]
name = "pypad"
version = "0.1.0"
description = "Python/Arduino based keypad with analog joystick for games/macros"
authors = [
    {name = "Anthony Post", email = "post.anthony@icloud.com"},
]
dependencies = [
    "python-dotenv",
    "ruff",
    "pyserial",
    "psutil",
    "pyyaml",
]
requires-python = "==3.12.*"
readme = "README.md"
license = {text = "MIT"}

[tool.pdm]
distribution = false
