[project]
name = "pypad"
version = "0.1.0"
description = "Default template for PDM package"
authors = [
    {name = "Anthony Post", email = "post.anthony@icloud.com"},
]
dependencies = [
    "black",
    "python-dotenv",
    "ruff",
    "pyserial",
    "psutil",
    "pyyaml",
    "tonberry",
]
requires-python = "==3.12.*"
readme = "README.md"
license = {text = "MIT"}


[tool.pdm]
distribution = false
